#include <types.h>
#include <interrupt.h>
#include <cpu.h>
#include <descriptor.h>
#include <video.h>
#include <strings.h>


void interrupt_dummy_noerrcode(interrupt_frame_t*, uint16_t );
void interrupt_dummy_errcode(interrupt_frame_t*, interrupt_errcode_t, uint16_t );
void interrupt_register_dummy_handlers(descriptor_idt_t*);

void interrupt_init() {
	descriptor_idt_t* idt_table = (descriptor_idt_t*)IDT_REGISTER.base;

	interrupt_register_dummy_handlers(idt_table); // 32-255 dummy handlers
	cpu_sti();
}


void interrupt_dummy_noerrcode(interrupt_frame_t* frame, uint16_t intnum){
	cpu_cli();
	video_print("Uncached interrupt occured without error code.\0");
	video_print("\r\nInterrupt number: \0");
	video_print(itoh(intnum));
	video_print("\r\nReturn address: \0");
	video_print(itoh(frame->return_rip));
	video_print("\r\nCpu is halting.\0");
	cpu_halt();
}

void interrupt_dummy_errcode(interrupt_frame_t* frame, interrupt_errcode_t errcode, uint16_t intnum){
	cpu_cli();
	video_print("Uncached interrupt occured with error code.\0");
	video_print("\r\nInterrupt number: \0");
	video_print(itoh(intnum));
	video_print("\r\nReturn address: \0");
	video_print(itoh(frame->return_rip));
	video_print("\r\nError code: \0");
	video_print(itoh(errcode));
	video_print("\r\nCpu is halting.\0");
	cpu_halt();
}

// the fucking ugly code generated by m4
#ifndef ___DEPEND_ANALYSIS
#include "../cc-gen/interrupt_handlers.c"
#endif
