# This work is licensed under TURNSTONE OS Public License.
# Please read and understand latest version of Licence.

FROM docker.io/library/alpine:3.17
RUN  apk add gcc valgrind-dev make findutils bash curl musl-dev && rm -fr /var/cache/apk/*
WORKDIR /osdev
CMD make clean gendirs qemu
