/**
 * @file asm_insts_p.64.c
 * @brief x86_64 assembly instruction mnemonics starting with 'p'
 *
 * This work is licensed under TURNSTONE OS Public License.
 * Please read and understand latest version of Licence.
 */

#include <compiler/asm_instructions.h>

MODULE("turnstone.compiler.assembler");

const asm_instruction_t asm_instructions_p[] = {
    {"pop", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_GS},
     2, {0x0f, 0xa9, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_GS},
     2, {0x0f, 0xa9, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_GS},
     2, {0x0f, 0xa9, }, false, false, 0, true, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_FS},
     2, {0x0f, 0xa1, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_FS},
     2, {0x0f, 0xa1, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_FS},
     2, {0x0f, 0xa1, }, false, false, 0, true, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_SS},
     1, {0x17, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_ES},
     1, {0x07, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_DS},
     1, {0x1f, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_R_64},
     1, {0x58, }, false, true, 'r', false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_R_32},
     1, {0x58, }, false, true, 'r', false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_R_16},
     1, {0x58, }, false, true, 'r', true, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pop", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_R_OR_M_64},
     1, {0x8f, }, true, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_RM_REG, },
    {"pop", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_R_OR_M_32},
     1, {0x8f, }, true, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_RM_REG, },
    {"pop", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_POP, ASM_INSTRUCTION_MNEMONIC_R_OR_M_16},
     1, {0x8f, }, true, false, 0, true, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_RM_REG, },

    {"popf", true, true,
     1, {ASM_INSTRUCTION_MNEMONIC_POPF, },
     1, {0x9d, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"popfd", false, true,
     1, {ASM_INSTRUCTION_MNEMONIC_POPFD, },
     1, {0x9d, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"popfq", true, false,
     1, {ASM_INSTRUCTION_MNEMONIC_POPFQ, },
     1, {0x9d, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },





    {"push", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_GS},
     2, {0x0f, 0xa8, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_FS},
     2, {0x0f, 0xa0, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_ES},
     1, {0x06, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_DS},
     1, {0x1e, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_SS},
     1, {0x16, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_CS},
     1, {0x0e, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_IMM_8},
     1, {0x6A, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_IMM, },
    {"push", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_IMM_32},
     1, {0x68, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_IMM, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_IMM_16},
     1, {0x68, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_IMM, },
    {"push", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_R_64},
     1, {0x50, }, false, true, 'r', false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_R_32},
     1, {0x50, }, false, true, 'r', false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_R_16},
     1, {0x50, }, false, true, 'r', true, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"push", true, false,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_R_OR_M_64},
     1, {0xff, }, true, false, 6, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_REG_RM, },
    {"push", false, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_R_OR_M_32},
     1, {0xff, }, true, false, 6, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_REG_RM, },
    {"push", true, true,
     2, {ASM_INSTRUCTION_MNEMONIC_PUSH, ASM_INSTRUCTION_MNEMONIC_R_OR_M_16},
     1, {0xff, }, true, false, 6, true, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_REG_RM, },

    {"pushf", true, true,
     1, {ASM_INSTRUCTION_MNEMONIC_PUSHF, },
     1, {0x9c, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pushfd", false, true,
     1, {ASM_INSTRUCTION_MNEMONIC_PUSHFD, },
     1, {0x9c, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
    {"pushfq", true, false,
     1, {ASM_INSTRUCTION_MNEMONIC_PUSHFQ, },
     1, {0x9c, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },


    // end of table
    {NULL, false, false, 0, {0, }, 0, {0, }, false, false, 0, false, false, false, false, ASM_INSTRUCTION_OPERAND_ENCODE_NULL, },
};
