/**
 * @file mlkem768.h
 * @brief ML-KEM-768 implementation header
 *
 * This file provides the interface for the ML-KEM-768 (Module Lattice-based Key Encapsulation Mechanism)
 * algorithm, a post-quantum cryptography standard defined by NIST. It includes functions for key
 * generation, encapsulation (encryption), and decapsulation (decryption).
 *
 * ML-KEM-768 is part of the NIST PQC standardization process and offers a balance between security
 * and performance for lattice-based cryptography.
 *
 * This work is licensed under TURNSTONE OS Public License.
 * Please read and understand latest version of Licence.
 */

#ifndef ___MLKEM768_H
#define ___MLKEM768_H

#ifdef __cplusplus
extern "C" {
#endif

#include <types.h>


/**
 * @brief The number of bytes in the shared secret generated by ML-KEM-768.
 *
 * This is the size of the symmetric key that can be derived from the encapsulation process.
 */
#define MLKEM768_SHARED_SECRET_BYTES 32

/**
 * @brief The number of bytes in the public key for ML-KEM-768.
 *
 * This includes the public polynomial coefficients and potentially other related data.
 */
#define MLKEM768_PUBLICKEYBYTES 1184 // 3 polynomials of 384 bytes each + 32 bytes for seed = 1152 + 32 = 1184 bytes

/**
 * @brief The number of bytes in the ciphertext produced by ML-KEM-768 encapsulation.
 *
 * This consists of the encapsulated polynomial 'u' and the polynomial 'v'.
 */
#define MLKEM768_CIPHERTEXTBYTES  1088 // 960 bytes for u + 128 bytes for v = 1088 bytes

/**
 * @brief The number of bytes in the secret key for ML-KEM-768.
 *
 * This includes the secret polynomial coefficients, the public key, and other necessary components
 * for decryption.
 */
#define MLKEM768_SECRETKEYBYTES 2400 // 3 polynomials of 384 bytes each + 1184 bytes for public key + 32 bytes for H(pk) + 32 bytes for z = 1152 + 1184 + 32 + 32 = 2400 bytes

/**
 * @brief Generates a public and secret key pair for ML-KEM-768.
 *
 * This function implements the key generation algorithm for ML-KEM-768. It produces a public key
 * that can be shared and a corresponding secret key that must be kept confidential.
 *
 * @param pk Pointer to a buffer where the public key will be stored. Must be at least MLKEM768_PUBLICKEYBYTES in size.
 * @param sk Pointer to a buffer where the secret key will be stored. Must be at least MLKEM768_SECRETKEYBYTES in size.
 */
void mlkem768_keygen(uint8_t * pk, uint8_t * sk);

/**
 * @brief Encapsulates a shared secret using the recipient's public key.
 *
 * This function performs the key encapsulation process. It takes the recipient's public key and
 * generates a shared secret along with a ciphertext that can be used to decrypt the secret.
 *
 * @param ct Pointer to a buffer where the resulting ciphertext will be stored. Must be at least MLKEM768_CIPHERTEXTBYTES in size.
 * @param ss Pointer to a buffer where the generated shared secret will be stored. Must be at least MLKEM768_SHARED_SECRET_BYTES in size.
 * @param pk Pointer to the recipient's public key. Must be at least MLKEM768_PUBLICKEYBYTES in size.
 */
void mlkem768_encaps(uint8_t * ct, uint8_t * ss, const uint8_t * pk);

/**
 * @brief Decapsulates a shared secret from a ciphertext using the secret key.
 *
 * This function performs the key decapsulation process. It takes a ciphertext and the corresponding
 * secret key to recover the original shared secret.
 *
 * @param ss Pointer to a buffer where the recovered shared secret will be stored. Must be at least MLKEM768_SHARED_SECRET_BYTES in size.
 * @param ct Pointer to the ciphertext generated during encapsulation. Must be at least MLKEM768_CIPHERTEXTBYTES in size.
 * @param sk Pointer to the recipient's secret key. Must be at least MLKEM768_SECRETKEYBYTES in size.
 */
void mlkem768_decaps(uint8_t * ss, const uint8_t * ct, const uint8_t * sk);


#ifdef __cplusplus
}
#endif

#endif
